In [15]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Mamtha H\Downloads\dataset.csv")
print(df)

     Patient_ID Admission_Date Discharge_Date   Age  Gender   Department  \
0       P100000            NaN     2025-10-20  29.0    Male    Neurology
1       P100001     2024-08-08     2024-08-19  46.0   Other   Cardiology
2       P100002     2025-04-09     2025-04-21  86.0   Other  Orthopedics
3       P100003     2025-08-03     2025-08-14  83.0  Female   Pediatrics
4       P100004     2025-04-24     2025-05-11   2.0    Male   Pediatrics
...         ...            ...            ...   ...     ...          ...
4995    P104995     2025-10-19     2025-10-30  27.0     NaN   Cardiology
4996    P104996     2025-02-07     2025-02-21   NaN  Female   Pediatrics
4997    P104997            NaN     2025-12-22  54.0  Female  Orthopedics
4998    P104998     2025-01-05     2025-01-21  81.0    Male          ENT
4999    P104999     2024-03-10     2024-03-12  47.0   Other    Neurology

         Diagnosis     Doctor  Length_of_Stay  Treatment_Cost Insurance  \
0              NaN  Dr. Meena             4.0        152127.0        No
1     Kidney Stone   Dr. John            11.0        169794.0        No
2           Asthma   Dr. John            12.0        185397.0        No
3         Migraine   Dr. John            11.0         41262.0       Yes
4           Cancer   Dr. John             NaN        194292.0        No
...            ...        ...             ...             ...       ...
4995  Kidney Stone  Dr. Meena            11.0        166370.0        No
4996  Hypertension  Dr. Arjun            14.0        126655.0        No
4997           NaN  Dr. Divya             7.0        100625.0       Yes
4998        Asthma  Dr. Priya             NaN        178609.0        No
4999        Asthma   Dr. Ravi             2.0          5956.0       Yes

             City Blood_Group Admission_Type          Outcome
0          Trichy          A+      Emergency  Under Treatment
1             NaN          B-      Emergency        Recovered
2         Chennai          A+        Routine         Improved
3      Coimbatore          B+        Routine         Referred
4         Madurai          A-        Routine         Deceased
...           ...         ...            ...              ...
4995  Tirunelveli          A-      Emergency  Under Treatment
4996        Erode         NaN       Referral         Improved
4997        Erode          A+       Referral         Improved
4998   Coimbatore         AB-       Referral        Recovered
4999        Salem          B-      Emergency         Improved

[5000 rows x 15 columns]

In [16]:
df.isnull().sum()

Patient_ID          0
Admission_Date    149
Discharge_Date    256
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [17]:
df.head()

,Patient_ID,Admission_Date,Discharge_Date,Age,Gender,Department,Diagnosis,Doctor,Length_of_Stay,Treatment_Cost,Insurance,City,Blood_Group,Admission_Type,Outcome
0,P100000,NaN,2025-10-20,29.0,Male,Neurology,NaN,Dr. Meena,4.0,152127.0,No,Trichy,A+,Emergency,Under Treatment
1,P100001,2024-08-08,2024-08-19,46.0,Other,Cardiology,Kidney Stone,Dr. John,11.0,169794.0,No,NaN,B-,Emergency,Recovered
2,P100002,2025-04-09,2025-04-21,86.0,Other,Orthopedics,Asthma,Dr. John,12.0,185397.0,No,Chennai,A+,Routine,Improved
3,P100003,2025-08-03,2025-08-14,83.0,Female,Pediatrics,Migraine,Dr. John,11.0,41262.0,Yes,Coimbatore,B+,Routine,Referred
4,P100004,2025-04-24,2025-05-11,2.0,Male,Pediatrics,Cancer,Dr. John,NaN,194292.0,No,Madurai,A-,Routine,Deceased

In [19]:
df.ffill()

,Patient_ID,Admission_Date,Discharge_Date,Age,Gender,Department,Diagnosis,Doctor,Length_of_Stay,Treatment_Cost,Insurance,City,Blood_Group,Admission_Type,Outcome
0,P100000,NaN,2025-10-20,29.0,Male,Neurology,NaN,Dr. Meena,4.0,152127.0,No,Trichy,A+,Emergency,Under Treatment
1,P100001,2024-08-08,2024-08-19,46.0,Other,Cardiology,Kidney Stone,Dr. John,11.0,169794.0,No,Trichy,B-,Emergency,Recovered
2,P100002,2025-04-09,2025-04-21,86.0,Other,Orthopedics,Asthma,Dr. John,12.0,185397.0,No,Chennai,A+,Routine,Improved
3,P100003,2025-08-03,2025-08-14,83.0,Female,Pediatrics,Migraine,Dr. John,11.0,41262.0,Yes,Coimbatore,B+,Routine,Referred
4,P100004,2025-04-24,2025-05-11,2.0,Male,Pediatrics,Cancer,Dr. John,11.0,194292.0,No,Madurai,A-,Routine,Deceased
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,P104995,2025-10-19,2025-10-30,27.0,Female,Cardiology,Kidney Stone,Dr. Meena,11.0,166370.0,No,Tirunelveli,A-,Emergency,Under Treatment
4996,P104996,2025-02-07,2025-02-21,27.0,Female,Pediatrics,Hypertension,Dr. Arjun,14.0,126655.0,No,Erode,A-,Referral,Improved
4997,P104997,2025-02-07,2025-12-22,54.0,Female,Orthopedics,Hypertension,Dr. Divya,7.0,100625.0,Yes,Erode,A+,Referral,Improved
4998,P104998,2025-01-05,2025-01-21,81.0,Male,ENT,Asthma,Dr. Priya,7.0,178609.0,No,Coimbatore,AB-,Referral,Recovered
4999,P104999,2024-03-10,2024-03-12,47.0,Other,Neurology,Asthma,Dr. Ravi,2.0,5956.0,Yes,Salem,B-,Emergency,Improved

In [20]:
df.isnull().sum()

Patient_ID          0
Admission_Date    149
Discharge_Date    256
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [21]:
df.bfill()

,Patient_ID,Admission_Date,Discharge_Date,Age,Gender,Department,Diagnosis,Doctor,Length_of_Stay,Treatment_Cost,Insurance,City,Blood_Group,Admission_Type,Outcome
0,P100000,2024-08-08,2025-10-20,29.0,Male,Neurology,Kidney Stone,Dr. Meena,4.0,152127.0,No,Trichy,A+,Emergency,Under Treatment
1,P100001,2024-08-08,2024-08-19,46.0,Other,Cardiology,Kidney Stone,Dr. John,11.0,169794.0,No,Chennai,B-,Emergency,Recovered
2,P100002,2025-04-09,2025-04-21,86.0,Other,Orthopedics,Asthma,Dr. John,12.0,185397.0,No,Chennai,A+,Routine,Improved
3,P100003,2025-08-03,2025-08-14,83.0,Female,Pediatrics,Migraine,Dr. John,11.0,41262.0,Yes,Coimbatore,B+,Routine,Referred
4,P100004,2025-04-24,2025-05-11,2.0,Male,Pediatrics,Cancer,Dr. John,12.0,194292.0,No,Madurai,A-,Routine,Deceased
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,P104995,2025-10-19,2025-10-30,27.0,Female,Cardiology,Kidney Stone,Dr. Meena,11.0,166370.0,No,Tirunelveli,A-,Emergency,Under Treatment
4996,P104996,2025-02-07,2025-02-21,54.0,Female,Pediatrics,Hypertension,Dr. Arjun,14.0,126655.0,No,Erode,A+,Referral,Improved
4997,P104997,2025-01-05,2025-12-22,54.0,Female,Orthopedics,Asthma,Dr. Divya,7.0,100625.0,Yes,Erode,A+,Referral,Improved
4998,P104998,2025-01-05,2025-01-21,81.0,Male,ENT,Asthma,Dr. Priya,2.0,178609.0,No,Coimbatore,AB-,Referral,Recovered
4999,P104999,2024-03-10,2024-03-12,47.0,Other,Neurology,Asthma,Dr. Ravi,2.0,5956.0,Yes,Salem,B-,Emergency,Improved

In [22]:
df.isnull().sum()

Patient_ID          0
Admission_Date    149
Discharge_Date    256
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [23]:
df.fillna(0)

,Patient_ID,Admission_Date,Discharge_Date,Age,Gender,Department,Diagnosis,Doctor,Length_of_Stay,Treatment_Cost,Insurance,City,Blood_Group,Admission_Type,Outcome
0,P100000,0,2025-10-20,29.0,Male,Neurology,0,Dr. Meena,4.0,152127.0,No,Trichy,A+,Emergency,Under Treatment
1,P100001,2024-08-08,2024-08-19,46.0,Other,Cardiology,Kidney Stone,Dr. John,11.0,169794.0,No,0,B-,Emergency,Recovered
2,P100002,2025-04-09,2025-04-21,86.0,Other,Orthopedics,Asthma,Dr. John,12.0,185397.0,No,Chennai,A+,Routine,Improved
3,P100003,2025-08-03,2025-08-14,83.0,Female,Pediatrics,Migraine,Dr. John,11.0,41262.0,Yes,Coimbatore,B+,Routine,Referred
4,P100004,2025-04-24,2025-05-11,2.0,Male,Pediatrics,Cancer,Dr. John,0.0,194292.0,No,Madurai,A-,Routine,Deceased
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,P104995,2025-10-19,2025-10-30,27.0,0,Cardiology,Kidney Stone,Dr. Meena,11.0,166370.0,No,Tirunelveli,A-,Emergency,Under Treatment
4996,P104996,2025-02-07,2025-02-21,0.0,Female,Pediatrics,Hypertension,Dr. Arjun,14.0,126655.0,No,Erode,0,Referral,Improved
4997,P104997,0,2025-12-22,54.0,Female,Orthopedics,0,Dr. Divya,7.0,100625.0,Yes,Erode,A+,Referral,Improved
4998,P104998,2025-01-05,2025-01-21,81.0,Male,ENT,Asthma,Dr. Priya,0.0,178609.0,No,Coimbatore,AB-,Referral,Recovered
4999,P104999,2024-03-10,2024-03-12,47.0,Other,Neurology,Asthma,Dr. Ravi,2.0,5956.0,Yes,Salem,B-,Emergency,Improved

In [24]:
df.isnull().sum()

Patient_ID          0
Admission_Date    149
Discharge_Date    256
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [26]:
df["Admission_Date"]=df["Admission_Date"].ffill()

In [27]:
df.isnull().sum()

Patient_ID          0
Admission_Date      1
Discharge_Date    256
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [28]:
df["Admission_Date"]=df["Admission_Date"].fillna(0)

In [29]:
df.isnull().sum()

Patient_ID          0
Admission_Date      0
Discharge_Date    256
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [31]:
df["Discharge_Date"]=df["Discharge_Date"].ffill()

In [32]:
df.isnull().sum()

Patient_ID          0
Admission_Date      0
Discharge_Date      0
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [33]:
df["Age"]=df["Age"].bfill()

In [34]:
df.isnull().sum()

Patient_ID          0
Admission_Date      0
Discharge_Date      0
Age                 0
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [35]:
df["Gender"]=df["Gender"].ffill()

In [36]:
df.isnull().sum()

Patient_ID          0
Admission_Date      0
Discharge_Date      0
Age                 0
Gender              0
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [37]:
df["Department"]=df["Department"].ffill()

In [38]:
df["Diagnosis"]=df["Diagnosis"].ffill()

In [39]:
df["Outcome"]=df["Outcome"].ffill()

In [40]:
df["Insurance"]=df["Insurance"].ffill()

In [41]:
df["City"]=df["City"].ffill()

In [42]:
df["Doctor"]=df["Doctor"].ffill()

In [43]:
df.isnull().sum()

Patient_ID          0
Admission_Date      0
Discharge_Date      0
Age                 0
Gender              0
Department          0
Diagnosis           1
Doctor              0
Length_of_Stay    273
Treatment_Cost    269
Insurance           0
City                0
Blood_Group       207
Admission_Type    270
Outcome             0
dtype: int64

In [44]:
df["Treatment_Cost"]=df["Treatment_Cost"].ffill()

In [45]:
df["Length_of_Stay"]=df["Length_of_Stay"].ffill()

In [46]:
df["Blood_Group"]=df["Blood_Group"].ffill()

In [47]:
df["Admission_Type"]=df["Admission_Type"].ffill()

In [48]:
df.isnull().sum()

Patient_ID        0
Admission_Date    0
Discharge_Date    0
Age               0
Gender            0
Department        0
Diagnosis         1
Doctor            0
Length_of_Stay    0
Treatment_Cost    0
Insurance         0
City              0
Blood_Group       0
Admission_Type    0
Outcome           0
dtype: int64

In [49]:
df["Doctor"]=df["Doctor"].bfill()

In [50]:
df.isnull().sum()

Patient_ID        0
Admission_Date    0
Discharge_Date    0
Age               0
Gender            0
Department        0
Diagnosis         1
Doctor            0
Length_of_Stay    0
Treatment_Cost    0
Insurance         0
City              0
Blood_Group       0
Admission_Type    0
Outcome           0
dtype: int64

In [51]:
df["Diagnosis"]=df["Diagnosis"].bfill()

In [52]:
df.isnull().sum()

Patient_ID        0
Admission_Date    0
Discharge_Date    0
Age               0
Gender            0
Department        0
Diagnosis         0
Doctor            0
Length_of_Stay    0
Treatment_Cost    0
Insurance         0
City              0
Blood_Group       0
Admission_Type    0
Outcome           0
dtype: int64

In [2]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Mamtha H\Downloads\dataset.csv")
print(df)

     Patient_ID Admission_Date Discharge_Date   Age  Gender   Department  \
0       P100000            NaN     2025-10-20  29.0    Male    Neurology
1       P100001     2024-08-08     2024-08-19  46.0   Other   Cardiology
2       P100002     2025-04-09     2025-04-21  86.0   Other  Orthopedics
3       P100003     2025-08-03     2025-08-14  83.0  Female   Pediatrics
4       P100004     2025-04-24     2025-05-11   2.0    Male   Pediatrics
...         ...            ...            ...   ...     ...          ...
4995    P104995     2025-10-19     2025-10-30  27.0     NaN   Cardiology
4996    P104996     2025-02-07     2025-02-21   NaN  Female   Pediatrics
4997    P104997            NaN     2025-12-22  54.0  Female  Orthopedics
4998    P104998     2025-01-05     2025-01-21  81.0    Male          ENT
4999    P104999     2024-03-10     2024-03-12  47.0   Other    Neurology

         Diagnosis     Doctor  Length_of_Stay  Treatment_Cost Insurance  \
0              NaN  Dr. Meena             4.0        152127.0        No
1     Kidney Stone   Dr. John            11.0        169794.0        No
2           Asthma   Dr. John            12.0        185397.0        No
3         Migraine   Dr. John            11.0         41262.0       Yes
4           Cancer   Dr. John             NaN        194292.0        No
...            ...        ...             ...             ...       ...
4995  Kidney Stone  Dr. Meena            11.0        166370.0        No
4996  Hypertension  Dr. Arjun            14.0        126655.0        No
4997           NaN  Dr. Divya             7.0        100625.0       Yes
4998        Asthma  Dr. Priya             NaN        178609.0        No
4999        Asthma   Dr. Ravi             2.0          5956.0       Yes

             City Blood_Group Admission_Type          Outcome
0          Trichy          A+      Emergency  Under Treatment
1             NaN          B-      Emergency        Recovered
2         Chennai          A+        Routine         Improved
3      Coimbatore          B+        Routine         Referred
4         Madurai          A-        Routine         Deceased
...           ...         ...            ...              ...
4995  Tirunelveli          A-      Emergency  Under Treatment
4996        Erode         NaN       Referral         Improved
4997        Erode          A+       Referral         Improved
4998   Coimbatore         AB-       Referral        Recovered
4999        Salem          B-      Emergency         Improved

[5000 rows x 15 columns]

In [3]:
df.isnull().sum()

Patient_ID          0
Admission_Date    149
Discharge_Date    256
Age               311
Gender            209
Department        246
Diagnosis         402
Doctor            341
Length_of_Stay    273
Treatment_Cost    269
Insurance         262
City              240
Blood_Group       207
Admission_Type    270
Outcome           206
dtype: int64

In [4]:
df["Admission_Date"]=df["Admission_Date"].bfill()

In [5]:
df["Diagnosis"]=df["Diagnosis"].bfill()

In [6]:
df["Doctor"]=df["Doctor"].bfill()

In [7]:
df["Treatment_Cost"]=df["Treatment_Cost"].ffill()

In [8]:
df["Length_of_Stay"]=df["Length_of_Stay"].ffill()

In [9]:
df["Blood_Group"]=df["Blood_Group"].ffill()

In [10]:
df["Admission_Type"]=df["Admission_Type"].ffill()

In [11]:
df["Department"]=df["Department"].ffill()

In [12]:
df["Outcome"]=df["Outcome"].ffill()

In [13]:
df["Insurance"]=df["Insurance"].ffill()

In [14]:
df["City"]=df["City"].ffill()

In [15]:
df.isnull().sum()

Patient_ID          0
Admission_Date      0
Discharge_Date    256
Age               311
Gender            209
Department          0
Diagnosis           0
Doctor              0
Length_of_Stay      0
Treatment_Cost      0
Insurance           0
City                0
Blood_Group         0
Admission_Type      0
Outcome             0
dtype: int64

In [16]:
df["Discharge_Date"]=df["Discharge_Date"].ffill()

In [17]:
df["Gender"]=df["Gender"].ffill()

In [18]:
df["Age"]=df["Age"].bfill()

In [19]:
df.isnull().sum()

Patient_ID        0
Admission_Date    0
Discharge_Date    0
Age               0
Gender            0
Department        0
Diagnosis         0
Doctor            0
Length_of_Stay    0
Treatment_Cost    0
Insurance         0
City              0
Blood_Group       0
Admission_Type    0
Outcome           0
dtype: int64

In [20]:
df.head()

,Patient_ID,Admission_Date,Discharge_Date,Age,Gender,Department,Diagnosis,Doctor,Length_of_Stay,Treatment_Cost,Insurance,City,Blood_Group,Admission_Type,Outcome
0,P100000,2024-08-08,2025-10-20,29.0,Male,Neurology,Kidney Stone,Dr. Meena,4.0,152127.0,No,Trichy,A+,Emergency,Under Treatment
1,P100001,2024-08-08,2024-08-19,46.0,Other,Cardiology,Kidney Stone,Dr. John,11.0,169794.0,No,Trichy,B-,Emergency,Recovered
2,P100002,2025-04-09,2025-04-21,86.0,Other,Orthopedics,Asthma,Dr. John,12.0,185397.0,No,Chennai,A+,Routine,Improved
3,P100003,2025-08-03,2025-08-14,83.0,Female,Pediatrics,Migraine,Dr. John,11.0,41262.0,Yes,Coimbatore,B+,Routine,Referred
4,P100004,2025-04-24,2025-05-11,2.0,Male,Pediatrics,Cancer,Dr. John,11.0,194292.0,No,Madurai,A-,Routine,Deceased

In [21]:
df.tail()

,Patient_ID,Admission_Date,Discharge_Date,Age,Gender,Department,Diagnosis,Doctor,Length_of_Stay,Treatment_Cost,Insurance,City,Blood_Group,Admission_Type,Outcome
4995,P104995,2025-10-19,2025-10-30,27.0,Female,Cardiology,Kidney Stone,Dr. Meena,11.0,166370.0,No,Tirunelveli,A-,Emergency,Under Treatment
4996,P104996,2025-02-07,2025-02-21,54.0,Female,Pediatrics,Hypertension,Dr. Arjun,14.0,126655.0,No,Erode,A-,Referral,Improved
4997,P104997,2025-01-05,2025-12-22,54.0,Female,Orthopedics,Asthma,Dr. Divya,7.0,100625.0,Yes,Erode,A+,Referral,Improved
4998,P104998,2025-01-05,2025-01-21,81.0,Male,ENT,Asthma,Dr. Priya,7.0,178609.0,No,Coimbatore,AB-,Referral,Recovered
4999,P104999,2024-03-10,2024-03-12,47.0,Other,Neurology,Asthma,Dr. Ravi,2.0,5956.0,Yes,Salem,B-,Emergency,Improved

In [25]:
df.to_csv(R"C:\Users\Mamtha H\Downloads\dataset.csv", index=False)

In [26]:
print(df)

     Patient_ID Admission_Date Discharge_Date   Age  Gender   Department  \
0       P100000     2024-08-08     2025-10-20  29.0    Male    Neurology
1       P100001     2024-08-08     2024-08-19  46.0   Other   Cardiology
2       P100002     2025-04-09     2025-04-21  86.0   Other  Orthopedics
3       P100003     2025-08-03     2025-08-14  83.0  Female   Pediatrics
4       P100004     2025-04-24     2025-05-11   2.0    Male   Pediatrics
...         ...            ...            ...   ...     ...          ...
4995    P104995     2025-10-19     2025-10-30  27.0  Female   Cardiology
4996    P104996     2025-02-07     2025-02-21  54.0  Female   Pediatrics
4997    P104997     2025-01-05     2025-12-22  54.0  Female  Orthopedics
4998    P104998     2025-01-05     2025-01-21  81.0    Male          ENT
4999    P104999     2024-03-10     2024-03-12  47.0   Other    Neurology

         Diagnosis     Doctor  Length_of_Stay  Treatment_Cost Insurance  \
0     Kidney Stone  Dr. Meena             4.0        152127.0        No
1     Kidney Stone   Dr. John            11.0        169794.0        No
2           Asthma   Dr. John            12.0        185397.0        No
3         Migraine   Dr. John            11.0         41262.0       Yes
4           Cancer   Dr. John            11.0        194292.0        No
...            ...        ...             ...             ...       ...
4995  Kidney Stone  Dr. Meena            11.0        166370.0        No
4996  Hypertension  Dr. Arjun            14.0        126655.0        No
4997        Asthma  Dr. Divya             7.0        100625.0       Yes
4998        Asthma  Dr. Priya             7.0        178609.0        No
4999        Asthma   Dr. Ravi             2.0          5956.0       Yes

             City Blood_Group Admission_Type          Outcome
0          Trichy          A+      Emergency  Under Treatment
1          Trichy          B-      Emergency        Recovered
2         Chennai          A+        Routine         Improved
3      Coimbatore          B+        Routine         Referred
4         Madurai          A-        Routine         Deceased
...           ...         ...            ...              ...
4995  Tirunelveli          A-      Emergency  Under Treatment
4996        Erode          A-       Referral         Improved
4997        Erode          A+       Referral         Improved
4998   Coimbatore         AB-       Referral        Recovered
4999        Salem          B-      Emergency         Improved

[5000 rows x 15 columns]

In [27]:
df.isnull().sum()

Patient_ID        0
Admission_Date    0
Discharge_Date    0
Age               0
Gender            0
Department        0
Diagnosis         0
Doctor            0
Length_of_Stay    0
Treatment_Cost    0
Insurance         0
City              0
Blood_Group       0
Admission_Type    0
Outcome           0
dtype: int64

In [28]:
df=df.to_csv(R"C:\Users\Mamtha H\Downloads\dataset.csv", index=False)
print("File save")

File save

In [29]:
print(df)

(None, None)

In [31]:
import pandas as pd
df=pd.read_csv(r"C:\Users\Mamtha H\Downloads\dataset.csv")
print(df)

     Patient_ID Admission_Date Discharge_Date   Age  Gender   Department  \
0       P100000     2024-08-08     2025-10-20  29.0    Male    Neurology
1       P100001     2024-08-08     2024-08-19  46.0   Other   Cardiology
2       P100002     2025-04-09     2025-04-21  86.0   Other  Orthopedics
3       P100003     2025-08-03     2025-08-14  83.0  Female   Pediatrics
4       P100004     2025-04-24     2025-05-11   2.0    Male   Pediatrics
...         ...            ...            ...   ...     ...          ...
4995    P104995     2025-10-19     2025-10-30  27.0  Female   Cardiology
4996    P104996     2025-02-07     2025-02-21  54.0  Female   Pediatrics
4997    P104997     2025-01-05     2025-12-22  54.0  Female  Orthopedics
4998    P104998     2025-01-05     2025-01-21  81.0    Male          ENT
4999    P104999     2024-03-10     2024-03-12  47.0   Other    Neurology

         Diagnosis     Doctor  Length_of_Stay  Treatment_Cost Insurance  \
0     Kidney Stone  Dr. Meena             4.0        152127.0        No
1     Kidney Stone   Dr. John            11.0        169794.0        No
2           Asthma   Dr. John            12.0        185397.0        No
3         Migraine   Dr. John            11.0         41262.0       Yes
4           Cancer   Dr. John            11.0        194292.0        No
...            ...        ...             ...             ...       ...
4995  Kidney Stone  Dr. Meena            11.0        166370.0        No
4996  Hypertension  Dr. Arjun            14.0        126655.0        No
4997        Asthma  Dr. Divya             7.0        100625.0       Yes
4998        Asthma  Dr. Priya             7.0        178609.0        No
4999        Asthma   Dr. Ravi             2.0          5956.0       Yes

             City Blood_Group Admission_Type          Outcome
0          Trichy          A+      Emergency  Under Treatment
1          Trichy          B-      Emergency        Recovered
2         Chennai          A+        Routine         Improved
3      Coimbatore          B+        Routine         Referred
4         Madurai          A-        Routine         Deceased
...           ...         ...            ...              ...
4995  Tirunelveli          A-      Emergency  Under Treatment
4996        Erode          A-       Referral         Improved
4997        Erode          A+       Referral         Improved
4998   Coimbatore         AB-       Referral        Recovered
4999        Salem          B-      Emergency         Improved

[5000 rows x 15 columns]

In [32]:
df.isnull().sum()

Patient_ID        0
Admission_Date    0
Discharge_Date    0
Age               0
Gender            0
Department        0
Diagnosis         0
Doctor            0
Length_of_Stay    0
Treatment_Cost    0
Insurance         0
City              0
Blood_Group       0
Admission_Type    0
Outcome           0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(0)

In [34]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      5000 non-null   str
 1   Admission_Date  5000 non-null   str
 2   Discharge_Date  5000 non-null   str
 3   Age             5000 non-null   float64
 4   Gender          5000 non-null   str
 5   Department      5000 non-null   str
 6   Diagnosis       5000 non-null   str
 7   Doctor          5000 non-null   str
 8   Length_of_Stay  5000 non-null   float64
 9   Treatment_Cost  5000 non-null   float64
 10  Insurance       5000 non-null   str
 11  City            5000 non-null   str
 12  Blood_Group     5000 non-null   str
 13  Admission_Type  5000 non-null   str
 14  Outcome         5000 non-null   str
dtypes: float64(3), str(12)
memory usage: 586.1 KB

In [35]:
df.describe()

               Age  Length_of_Stay  Treatment_Cost
count  5000.000000     5000.000000     5000.000000
mean     45.988400       10.574400   126903.361800
std      25.922289        5.821412    70226.567465
min       1.000000        1.000000     5013.000000
25%      24.000000        6.000000    67083.750000
50%      47.000000       11.000000   125906.500000
75%      69.000000       16.000000   187246.750000
max      90.000000       20.000000   249987.000000